### ISSUE TITLE
Listen! (Navi voice)

### ISSUE THREAD

**Issue by xjackk** [jordandeang/ThisIsVT#1]
## Using Package Managers

You should get in the habit of using package managers for adding stuff to your project. This way they are all in one location and you dont have to manually grab them like you did and add them to your shit.

## Bower or NPM

You can use `bower` or `npm` to install Bootstrap

1. Make sure you have bower install globally. You should have `npm` if you downloaded Node.js.

`npm install -g bower`

2. `touch` (to create file!) `bower.json` or `package.json` for `bower` and/or `npm` respectively

Here is what my `bower.json` looks like for my one small project.

```
{
  "name": "writings",
  "dependencies": {
      "bootstrap": "*",
      "font-awesome": "*"
 }
}

```
3. `bower install` once you have the `bower.json` will grab all the dependencies and put them in a `bower_components` folder in your project. 

* The `*` character simply means it will grab the latest version of the package

Hope this helps a bit! This weekend I will help you write the frontend.

**Comment by jordandeang** [comment]
Thanks for the help, I installed bower globally and initialized a `bower.json` that installs Bootstrap, font-awesome and jquery. Accessing the static files in `bower-components` from `base.html` didn't work until I manually moved the directory to `app/static/`, though.

[This blog post] (http://statusq.org/archives/2014/10/25/6161/) explains that people would typically use grunt to automatically move the parts to their appropriate location, and it said that I can make a `.bowerrc` file that would move `bower_components` to a specified location, which is `app/static/` in my case. Since this is just a small project at the moment, I just made a `.bowerrc` file, but I'm not positive if this is a good idea.

Will bower handle most of the front-end dependencies

**Comment by xjackk** [comment]
`bower_components` is typically front-end shit, like jquery and such. `npm` will handle back-end packages like `express` and such.

I use `gulp.js` which is a streaming build step as opposed to Grunt. They are both the same thing though.

You can access the files in bower-components from anywhere in your project, really, you just have to make sure that you are properly linking the correct paths to the files. I didn't see any commit changes so I wasn't able to see if you did or not.

This Friday and Sunday I will be free to work, so I will grab you and help you write your front-end (:

Glad you checked out Bower (:
